version: '3.9'

services:
  db-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/challenge-eteg
    ports:
      - '5544:5432'
    volumes:
      - postgresdb:/var/lib/postgresql/data

  jd-form:
    container_name: js-form
    build:
      context: ./jd-form
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@localhost:5544/challenge-eteg
      - NEXTAUTH_URL="http://localhost:3000"
      - NEXTAUTH_SECRET="INzqFryqA4HHghDa0LTTt1pfBbElbbSvXvSg1Hn2K20="
      - NEXT_PUBLIC_JWT_SECRET_KEY="h/E16yRrziK9sGs9f/ZMOXscvbJvXXrPmad3g/77eXg="
      - NEXT_PUBLIC_UNSPLASH_URL="https://source.unsplash.com/random/?rainbow-background"
    volumes:
      - ./jd-form:/usr/src/app
    depends_on:
      - db-postgres
    restart: always

volumes:
  postgresdb: 