version: '3.9'

services:
  db-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/challenge-eteg
    ports:
      - '5544:5432'
    volumes:
      - postgresdb:/var/lib/postgresql/data

  jd-form:
    container_name: js-form
    build:
      context: ./jd-form
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=""
      - NEXTAUTH_URL=""
      - NEXTAUTH_SECRET=""
      - NEXT_PUBLIC_JWT_SECRET_KEY=""
      - NEXT_PUBLIC_UNSPLASH_URL=""
    volumes:
      - ./jd-form:/usr/src/app
    depends_on:
      - db-postgres
    restart: always

volumes:
  postgresdb: 
